#
# configuration for DaoPay payments via 
#
production:
  gateway_url:  http://daopay.com/pay/
  appcode:      54460
  successurl:  http://localhost/I_am_happy
  currency:     EUR
  style:        
  mcx:
    
testing:
  gateway_url:  http://daopay.com/pay/
  appcode:      54460
  successurl:  http://localhost/I_am_happy
  currency:     EUR
  style:        
  mcx:
    
development:
  gateway_url:  http://daopay.com/pay/
  appcode:      54460
  #successurl:  http://localhost/I_am_happy
  successurl:   
  currency:     EUR
  style:        
  mcx:          